### ISSUE TITLE
Rename project and npm package to github-manager-cli

### ISSUE THREAD

**Issue by charithsoori** [99xt/github-manager-cli#17]

**Comment by wiewioraseb** [comment]
I will work on it.

**Comment by wiewioraseb** [comment]
To rename a project and npm package, you have to do the following steps:
- To change project name execute:

`$ git remote set-url origin git@github.com:99xt/github-manager-cli`

or if you are using HTTPS instead of SSH:

`$ git remote set-url origin https://github.com/99xt/github-manager-cli.git`
  
- Regarding rename npm package:  

You can't really do it. You have to create a new one. 
But first you have to label the old one with 'deprecated' notification:

`$ npm deprecate github-label-maker@1.0.0 "WARNING: This module has been renamed to github-manager-cli. Please install it instead. See https://github.com/99xt/github-manager-cli for more information." `

After this, accept my pull request #18 with package name change to `github-manager-cli` and execute:
`$ npm publish`

**Comment by charithsoori** [comment]
to complete this issue you can rename package.json file and update the  pull request

https://github.com/99xt/github-manager-cli

**Comment by winniehell** [comment]
@charithsoori It looks like this is solved. Could you close it or remove the hacktoberfest label?

**Comment by rajikaimal** [comment]
Done.
